### ISSUE TITLE
Stopped using version numbers on AUR?

### ISSUE THREAD

**Issue by TurtleMeds** [kRHYME7/Hyprdots-ctl#19]
yay is flagging this package as newer than the latest AUR version, when it isn't. [It seems](https://aur.archlinux.org/cgit/aur.git/log/?h=hyprdots-ctl) like the issue is that you stopped the usage of version numbers. Why is this?

**Comment by kRHYME7** [comment]
> yay is flagging this package as newer than the latest AUR version, when it isn't. [It seems](https://aur.archlinux.org/cgit/aur.git/log/?h=hyprdots-ctl) like the issue is that you stopped the usage of version numbers. Why is this?


It needs extra work bumping the AUR. 
 So the PKGBUILD now will always dynamically follow the latest git version. Meaning the  first package version displayed will be stagnant like other ``` package-git ``` does. 
AUR helpers still fetch the latest commit  because the source is prefixed with ``` git+https://github.com/kRHYME7/Hyprdots-ctl.git ```

Then added a function to dynamically get the latest commit tag which effectively replace the ``` pkgver ``` variable


![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/53417443/c2f0b29c-b411-4d91-9e8a-18bd8ee6ce45)

![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/53417443/5ac62279-91c4-430b-8721-36d915eb430c)


So you can ignore the warning here.

**Comment by kRHYME7** [comment]
1 more thing, the link is the commit message. Now I am not manually/scripting the process therefore making them blank. I still control the version on github to make this flexible.

![image](https://github.com/kRHYME7/Hyprdots-ctl/assets/53417443/1ad5ba2c-3eaa-47e0-b944-d11edaa9f19d)

**Comment by kRHYME7** [comment]
hyprdots-ctl will be moved to hyprdots-ctl-git to comply with VCS standards. I did not notice this as paru manages different than yay.

**Comment by kRHYME7** [comment]
@TurtleMeds  ``` yay -Sy  hyprdots-ctl-git ```
